# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-23 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='created_time',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='parking_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parking',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
