# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-25 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20181024_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='parking_id',
            field=models.CharField(default=uuid.uuid1, max_length=100, primary_key=True, serialize=False),
        ),
    ]
